// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDN7wVnXxN7DjjG3twaNPFntUzF7fsTwGc',
    appId: '1:659413426484:android:7124148eb6ad43f8848561',
    messagingSenderId: '659413426484',
    projectId: 'racm-49f61',
    databaseURL: 'https://racm-49f61-default-rtdb.firebaseio.com',
    storageBucket: 'racm-49f61.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5qwht6L0wswl8JW1KNV-eLlDuTVnN03s',
    appId: '1:659413426484:ios:d61349a0bae6e79b848561',
    messagingSenderId: '659413426484',
    projectId: 'racm-49f61',
    databaseURL: 'https://racm-49f61-default-rtdb.firebaseio.com',
    storageBucket: 'racm-49f61.appspot.com',
    androidClientId: '659413426484-anaqd643hgufphd1smet6rjd03f9pgee.apps.googleusercontent.com',
    iosClientId: '659413426484-s9mnbgq8u2g6eavpo4ove5m1pm106u5p.apps.googleusercontent.com',
    iosBundleId: 'com.example.rac',
  );
}
